language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew clean assemble

sudo: false

branches:
  only:
    - master
    - develop
    - release

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/